# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: poc
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

variablesResolutionMode: 20210219
unresolvedVariablesNotificationMode: "error"
useDotenv: true

provider:
  name: aws
  runtime: python3.8
  logs:
      httpApi: true
  lambdaHashingVersion: 20201221
  stage: ${env:STAGE}
  region: ${env:REGION}
  environment:
      DB_URI: ${env:DB_URI}
      DB_CLUSTER_ARN: ${env:DB_CLUSTER_ARN}
      DB_SECRET_ARN: ${env:DB_SECRET_ARN}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "rds-data:ExecuteStatement"
            - "rds-data:BeginTransaction"
            - "rds-data:RollbackTransaction"
            - "secretsmanager:GetSecretValue"
          Resource: '*'

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  exclude:
    - node_modules/**
    - venv/**
    - .direnv/**  

functions:
  fastapp:
    handler: app.asgi.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'
#    Define function environment variables here
#    environment:
#      variable2: value2

custom:
  pythonRequirements:
      fileName: requirements/requirements.txt
      dockerizePip: non-linux

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-offline
